hw01-task01
ArgentumWalker/java-homework pull request #1
Opened 2016-09-12 16:07 UTC by ArgentumWalker

2016-09-17 21:15 UTC, yurii-litvinov commented on hw01/task01/src/ru/spbau/svidchenko/hashmap/Hashmap.java
> +
комментарии от комментируемой сущности обычно пустой строкой не отделяются

2016-09-17 21:16 UTC, yurii-litvinov commented on hw01/task01/src/ru/spbau/svidchenko/hashmap/Hashmap.java
> +     *Calls Hashmap::clear() inside
комментарии про детали реализации писать не нужно, вне класса это, в общем-то, никому не важно

2016-09-17 21:17 UTC, yurii-litvinov commented on hw01/task01/src/ru/spbau/svidchenko/hashmap/Hashmap.java
> +     *Calls Hashmap::clear() inside
комментарий обычно отделяют от * одним пробелом

2016-09-17 21:56 UTC, yurii-litvinov commented on hw01/task01/src/ru/spbau/svidchenko/hashmap/Hashmap.java
> +        return (elements[key.hashCode() % mod].find(key) != null);
hashCode() может вернуть отрицательное число, % тоже --- например, -13 % 5 == -3, так что рискованно

2016-09-17 21:58 UTC, yurii-litvinov commented on hw01/task01/src/ru/spbau/svidchenko/hashmap/Hashmap.java
> +     * @return count of elements in Hashmap
надо summary к методу. лучше не в @return это писать, а как-то так:

    /** Returns count of elements in Hashmap */

2016-09-17 22:00 UTC, yurii-litvinov commented on hw01/task01/src/ru/spbau/svidchenko/hashmap/Hashmap.java
> +     */
здесь и ниже тоже. первая строка JavaDoc-а --- это Summary, кусок документации, который показывается во всяких списках классов. если его вообще нет, то печаль. Summary и @return могут примерно дублировать друг друга, потому что в сгенерённом доке показываются в разных ситуациях

2016-09-17 22:01 UTC, yurii-litvinov commented on hw01/task01/src/ru/spbau/svidchenko/hashmap/Hashmap.java
> +        int i;
а зачем i объявляется здесь, она ведь используется только в цикле?

2016-09-17 22:02 UTC, yurii-litvinov commented on hw01/task01/src/ru/spbau/svidchenko/hashmap/Hashmap.java
> +        int i;
кстати, переменные без значения не имеют особого смысла. Вам ведь тут не важно, что это именованная область памяти, Вы просто хотите счётчик цикла

2016-09-17 22:03 UTC, yurii-litvinov commented on hw01/task01/src/ru/spbau/svidchenko/hashmap/Hashmap.java
> +                newElements[i] = new List ();
new List (); пишется как new List(); обычно

2016-09-17 22:03 UTC, yurii-litvinov commented on hw01/task01/src/ru/spbau/svidchenko/hashmap/List.java
> +        head = tail = null;
это лучше в две строчки делать, так читаемее

2016-09-17 22:04 UTC, yurii-litvinov commented on hw01/task01/src/ru/spbau/svidchenko/hashmap/List.java
> +            tail = head = n;
и тут. присваивание лучше всегда делать на отдельной строчке, чтобы оно было заметнее

2016-09-17 22:07 UTC, yurii-litvinov commented on hw01/task01/src/ru/spbau/svidchenko/hashmap/List.java
> +         */
чтобы такие мелкие комментарии не занимали три строчки, их можно писать в одну строчку и без @param --- 

    /** Sets new previous Node in List to prev */

2016-09-17 22:09 UTC, yurii-litvinov requested changes
желательно ещё выложить что-нибудь, что поможет собрать проект --- скрипт сборки, проектные файлы, смотря чем Вы пользуетесь. если просто вызываете компилятор из командной строки, это тоже можно сделать скриптом и выложить

2016-10-17 17:44 UTC, yurii-litvinov requested changes
Папку .gradle не надо выкладывать, это локальные файлы. Доисправляйте, пожалуйста.

2016-10-17 17:44 UTC, yurii-litvinov commented on hw01/task01/src/java/ru/spbau/svidchenko/hashmap/Hashmap.java
> +        return (elements[key.hashCode() % mod].find(key) != null);
key.hashCode() может быть отрицательным, что может оказаться неожиданным для хеш-таблицы.

2016-10-17 17:44 UTC, yurii-litvinov commented on hw01/task01/src/java/ru/spbau/svidchenko/hashmap/Hashmap.java
> +            elements[i] = new List ();
Здесь тоже перед "(" пробел не ставится.

2016-10-17 17:44 UTC, yurii-litvinov commented on hw01/task01/src/java/ru/spbau/svidchenko/hashmap/List.java
> +        tail = null;
Такую инициализацию сама Java сделает.

2016-11-13 15:33 UTC, yurii-litvinov requested changes
Сам gradle-wrapper.jar надо выкладывать, весь смысл gradle wrapper-а в том, что его можно просто запустить и он докачает всё нужное для сборки.

Доделайте, пожалуйста

2016-11-13 15:33 UTC, yurii-litvinov commented on hw01/task01/src/java/ru/spbau/svidchenko/hashmap/Hashmap.java
> +    /**Constructor for a Hashmap*/
Обычно комментируемый текст отделяется от комментария пробелом, так:
```java
/** Constructor for a Hashmap */
```

2016-11-13 15:33 UTC, yurii-litvinov commented on hw01/task01/src/java/ru/spbau/svidchenko/hashmap/Hashmap.java
> +        return elements[key.hashCode() % mod].find(key);
а тут Math.abs? :)

2016-11-13 15:33 UTC, yurii-litvinov commented on hw01/task01/src/java/ru/spbau/svidchenko/hashmap/Hashmap.java
> +        String result = elements[key.hashCode() % mod]
Может, имеет смысл вынести это в отдельный метод, чтобы не надо было копипастить Math.abs по всей программе, при этом в половине мест забыв поменять.

2016-11-13 15:33 UTC, yurii-litvinov commented on hw01/task01/src/java/ru/spbau/svidchenko/hashmap/Hashmap.java
> +        int i;
Кажется, i можно было объявить в заголовке for

2016-11-13 15:33 UTC, yurii-litvinov commented on hw01/task01/src/java/ru/spbau/svidchenko/hashmap/Hashmap.java
> +            newElements[elements[i].hashCode() % mod] = elements[i];
И тут abs нужно

2016-12-21 19:21 UTC, ArgentumWalker commented
Переписал все с начала.

2016-12-26 16:55 UTC, yurii-litvinov requested changes
Доисправляйте, пожалуйста

2016-12-26 16:55 UTC, yurii-litvinov commented on hw01/task01/src/main/java/ru/spbau/svidchenko/hw01/task01/MyHashMap.java
> +        List[] elements = new List[2*oldElements.length + 1];
"*" выделяется пробелами, как и любой арифметический оператор

2016-12-26 16:55 UTC, yurii-litvinov commented on hw01/task01/src/main/java/ru/spbau/svidchenko/hw01/task01/MyHashMap.java
> +        List[] elements = new List[2*oldElements.length + 1];
А точно имелся в виду новый elements, а не поле elements у класса? :)

2016-12-26 16:55 UTC, yurii-litvinov commented on hw01/task01/src/test/java/ru/spbau/svidchenko/hw01/task01/MyHashMapTest.java
> +            fail();
А чем assertEquals не подходит?

2016-12-26 16:55 UTC, yurii-litvinov commented on hw01/task01/src/test/java/ru/spbau/svidchenko/hw01/task01/MyHashMapTest.java
> +            fail();
Тут и ниже --- тоже, assertEquals, assertTrue и т.д.

2016-12-26 17:12 UTC, ArgentumWalker commented
Исправил

2016-12-26 17:15 UTC, yurii-litvinov approved these changes
Ок, зачтена

2016-12-26 17:15 UTC, yurii-litvinov commented on hw01/task01/src/test/java/ru/spbau/svidchenko/hw01/task01/MyHashMapTest.java
> +        assertEquals(map.put("A", "B"), "A");
Наоборот же, сначала ожидаемое значение, потом фактическое

2017-02-28 14:08 UTC, closed without merging