Hw03-task01
ArgentumWalker/java-homework pull request #4
Opened 2016-10-06 13:41 UTC by ArgentumWalker

2016-10-17 18:00 UTC, yurii-litvinov requested changes
Тесты не проходят. Поправьте, пожалуйста (и заодно уберите папку .gradle)

2016-10-17 18:00 UTC, yurii-litvinov commented on hw03/task01/src/main/java/ru/spbau/svidchenko/hw03/task01/Trie.java
> +    /** return true if contains such string */
Методы надо разделять пустыми строчками.

2016-10-17 18:00 UTC, yurii-litvinov commented on hw03/task01/src/main/java/ru/spbau/svidchenko/hw03/task01/Trie.java
> +        return true;
if (...) return false else return true можно записать как просто return !...;

2016-10-17 18:00 UTC, yurii-litvinov commented on hw03/task01/src/test/java/ru/spbau/svidchenko/hw03/task01/TrieTest.java
> +    Trie bor;
Мне кажется, его можно сделать private (и транслит --- это нехорошо).

2016-12-26 19:02 UTC, ArgentumWalker commented
Переписано

2016-12-26 19:48 UTC, yurii-litvinov requested changes
В целом всё так, но доисправляйте всё-таки, пожалуйста.

2016-12-26 19:48 UTC, yurii-litvinov commented on hw03/task01/src/main/java/ru/spbau/svidchenko/hw03/task01/Trie.java
> +        int childCount;
Его лучше было бы объявить в месте первого использования

2016-12-26 19:48 UTC, yurii-litvinov commented on hw03/task01/src/main/java/ru/spbau/svidchenko/hw03/task01/Trie.java
> +        //System.out.println("NotNull");
Закомментированный код и всякий отладочный вывод в продакшн-коде --- это плохо, перед пуллреквестом такие штуки обычно убирают

2016-12-26 19:48 UTC, yurii-litvinov commented on hw03/task01/src/test/java/ru/spbau/svidchenko/hw03/task01/TrieTest.java
> +    @Before
Тут бы не помешала пустая строчка

2016-12-26 19:48 UTC, yurii-litvinov commented on hw03/task01/src/test/java/ru/spbau/svidchenko/hw03/task01/TrieTest.java
> +            fail();
Ну опять :)

2016-12-26 19:48 UTC, yurii-litvinov commented on hw03/task01/src/test/java/ru/spbau/svidchenko/hw03/task01/TrieTest.java
> +    }
Неплохо бы ещё тут проверить, что произошло со строками после десериализации, находятся ли они ещё в бору.

2016-12-26 19:48 UTC, yurii-litvinov commented on hw03/task01/build.gradle
> +sourceCompatibility = 1.5
мм

2016-12-26 20:53 UTC, ArgentumWalker commented
Исправлено

2016-12-26 20:53 UTC, ArgentumWalker commented on hw03/task01/build.gradle
> +sourceCompatibility = 1.5
Это не я, оно само(

2016-12-26 21:09 UTC, yurii-litvinov approved these changes

2017-02-28 14:08 UTC, closed without merging