Hw04 task01
ArgentumWalker/java-homework pull request #5
Opened 2016-10-12 09:21 UTC by ArgentumWalker

2016-11-13 20:09 UTC, yurii-litvinov requested changes

2016-11-13 20:09 UTC, yurii-litvinov commented on hw04/task01/src/main/java/ru/spbau/svidchenko/hw04/task01/Maybe.java
> +    T content;
А зачем у него пакетная видимость?

2016-11-13 20:09 UTC, yurii-litvinov commented on hw04/task01/src/main/java/ru/spbau/svidchenko/hw04/task01/Maybe.java
> +    /** Make empty Maybe with nothing inside*/
Методы надо разделять пустыми строками.

2016-11-13 20:09 UTC, yurii-litvinov commented on hw04/task01/src/main/java/ru/spbau/svidchenko/hw04/task01/MaybeJustNullException.java
> +public class MaybeJustNullException extends Exception {
Тут тоже нужен более содержательный комментарий.

2016-11-13 20:09 UTC, yurii-litvinov commented on hw04/task01/src/main/java/ru/spbau/svidchenko/hw04/task01/MaybeNothingException.java
> +public class MaybeNothingException extends Exception {
И тут.

2016-11-13 20:09 UTC, yurii-litvinov commented on hw04/task01/src/main/java/ru/spbau/svidchenko/hw04/task01/NumSquaresWriter.java
> +        while(input.hasNextLine()) {
После while надо пробел.

2016-11-13 20:09 UTC, yurii-litvinov commented on hw04/task01/src/main/java/ru/spbau/svidchenko/hw04/task01/NumSquaresWriter.java
> +            } catch (Exception e) {
Лучше ловить более конкретные исключения.

2016-11-13 20:09 UTC, yurii-litvinov commented on hw04/task01/src/main/java/ru/spbau/svidchenko/hw04/task01/NumSquaresWriter.java
> +        while(input.hasNextLine()) {
Тут тоже пробела не хватает

2016-11-13 20:09 UTC, yurii-litvinov commented on hw04/task01/src/main/java/ru/spbau/svidchenko/hw04/task01/NumSquaresWriter.java
> +    }
А зачем два раза написано по сути одно и то же? readAndWrite --- это же конструктор NumSquaresWriter и write, копипаст суть ересь.

2016-11-13 20:09 UTC, yurii-litvinov commented on hw04/task01/src/test/java/ru/spbau/svidchenko/hw04/task01/MaybeTest.java
> +        }
Это же просто assertEquals((Integer)42, tmp.get());

2016-11-13 20:09 UTC, yurii-litvinov commented on hw04/task01/src/test/java/ru/spbau/svidchenko/hw04/task01/MaybeTest.java
> +        }
Вместо try-catch надо писать `@Test(expected = MaybeNothingException.class)`, чтобы было вот так:
```java
    @Test(expected = MaybeNothingException.class)
    public void NothingAndGetTest_GetNothing_ThrowsException() throws Exception {
        Maybe<Integer> tmp = Maybe.nothing();
        tmp.get();
    }
```

2016-12-26 17:04 UTC, yurii-litvinov requested changes

2016-12-26 17:04 UTC, yurii-litvinov commented on hw04/task01/src/test/java/ru/spbau/svidchenko/hw04/task01/MaybeTest.java
> +        }
up

2016-12-26 17:04 UTC, yurii-litvinov commented on hw04/task01/src/test/java/ru/spbau/svidchenko/hw04/task01/MaybeTest.java
> +        //if (tmp.map(MaybeTest::notNullMapper).isPresent()) {
Закомментированного кода быть не должно

2016-12-26 17:04 UTC, yurii-litvinov commented on hw04/task01/src/test/java/ru/spbau/svidchenko/hw04/task01/MaybeTest.java
> +        }
Напоминаю

2016-12-26 17:24 UTC, ArgentumWalker commented
Исправлено

2016-12-26 17:52 UTC, yurii-litvinov approved these changes
Гут, зачтена

2017-02-28 14:08 UTC, closed without merging